# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Identity
title: Jeremie Nlandu Mabiala - AI Engineer
firstName: Jérémie
lastName: Nlandu Mabiala
email: jeremie@aims.ac.za

# Profile Information
profile_alt: Jérémie Nlandu Mabiala - AI Engineer & Mathematical Modeling Researcher
profile_image: ./profile.jpeg
tagline: AI Master's Student | Mathematical Modeling Researcher | Teaching Assistant

# Location & Institution
location:
  name: African Institute for Mathematical Sciences (AIMS) Senegal
  url: https://aims-senegal.org/
  city: Mbour, Senegal
  icon: fa-solid fa-location-dot

# Navigation
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
  - blog.md
  - courses.md
  - contact.md

# Site Description
description: >- 
  AI Engineer and Mathematical Modeling Researcher passionate about advancing 
  artificial intelligence and mathematics in Africa. Currently pursuing AMMI 
  (African Master in Machine Intelligence) at AIMS Senegal. Specialized in 
  deep learning, computer vision, NLP, and mathematical optimization.

# Site Configuration
baseurl: "" 
url: "https://jnlandu.github.io"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc

github_repo: https://github.com/jnlandu/jnlandu.github.io/

# Pagination settings
pagination:
  enabled: true
  per_page: 5  # Number of posts per page
  permalink: "/page:num/"  # Optional: Customize the pagination URL

sitemap:
  exclude:
    - /contact.md
    - /404.html

# Social Media & SEO
social:
  name: Jeremie Nlandu Mabiala
  links:
    - https://twitter.com/ValentinMabiala
    - https://www.linkedin.com/in/jeremie-nlandu-mabiala-aa3a1b1b
    - https://github.com/jnlandu
    - mailto:jeremie@aims.ac.za

# Analytics & Verification
google_analytics: G-ZQTH7FZ9T4
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx

# Site Language
lang: en

# Professional Details
profession:
  current_role: AI Master's Student
  institution: AIMS Senegal
  program: African Master in Machine Intelligence (AMMI)
  research_interests:
    - Artificial Intelligence
    - Machine Learning
    - Deep Learning
    - Mathematical Modeling
    - Computer Vision
    - Natural Language Processing
    - Optimization
    - Statistical Learning

# AI Engineer Specializations
specializations:
  - name: Machine Learning
    level: advanced
    tools: [Python, PyTorch, TensorFlow, Scikit-learn]
  - name: Computer Vision
    level: intermediate
    tools: [OpenCV, PIL, Matplotlib]
  - name: Natural Language Processing
    level: intermediate
    tools: [NLTK, spaCy, Transformers]
  - name: Mathematical Modeling
    level: advanced
    tools: [NumPy, SciPy, R]

#  Updated theme schemas:
sass:
  sass_dir: _sass
  style: expanded
  # sourcemap: always
  # quiet_deps: false
  # verbose: false

collections:
  events:
    output: true
    permalink: /events/:title/
  tutorials:
    output: true
    permalink: /tutorials/:title/
  projects:
    output: true
    permalink: /projects/:title/
  courses:
    output: true
    permalink: /courses/:title/
  research:
    output: true
    permalink: /research/:title/

# Collection defaults for better SEO and organization
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
      author: "Jeremie Nlandu Mabiala"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Jeremie Nlandu Mabiala"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "post"
      toc: true
      author: "Jeremie Nlandu Mabiala"

    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
